/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jeremy_cameragmail_NativeLib */

#ifndef _Included_com_jeremy_cameragmail_NativeLib
#define _Included_com_jeremy_cameragmail_NativeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jeremy_cameragmail_NativeLib
 * Method:    account
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jeremy_cameragmail_NativeLib_account
  (JNIEnv *, jobject);

/*
 * Class:     com_jeremy_cameragmail_NativeLib
 * Method:    password
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_jeremy_cameragmail_NativeLib_password
  (JNIEnv *, jobject);

/*
 * Class:     com_jeremy_cameragmail_NativeLib
 * Method:    getRawKey
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_jeremy_cameragmail_NativeLib_getRawKey
  (JNIEnv *, jobject);

/*
 * Class:     com_jeremy_cameragmail_NativeLib
 * Method:    email
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jeremy_cameragmail_NativeLib_email
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
